# Generated by Django 2.2.4 on 2022-10-01 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0010_auto_20221001_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=datetime.datetime),
        ),
    ]
